const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');
const simpleGit = require('simple-git');

class PRSummaryGenerator {
  constructor(config) {
    this.config = config;
  }

  async generate() {
    const changes = await this.getChanges();
    const content = this.buildSummary(changes);
    await this.saveFile(content);
    return content;
  }

  async getChanges() {
    try {
      const git = simpleGit();
      const status = await git.status();
      const diff = await git.diff();
      
      return {
        files: status.files.map(f => f.path),
        additions: diff.split('\n').filter(line => line.startsWith('+')).length,
        deletions: diff.split('\n').filter(line => line.startsWith('-')).length,
        diff: diff
      };
    } catch (error) {
      console.warn(chalk.yellow('⚠️  Could not get git changes:', error.message));
      return {
        files: ['No git changes detected'],
        additions: 0,
        deletions: 0,
        diff: ''
      };
    }
  }

  buildSummary(changes) {
    const { title, branch, description, changes: selectedChanges, includeChecklist, includeTesting } = this.config;

    const changeTypes = {
      feature: '✨ New Feature',
      fix: '🐛 Bug Fix',
      docs: '📝 Documentation',
      refactor: '♻️ Refactoring',
      tests: '🧪 Tests',
      perf: '⚡ Performance'
    };

    let content = `# PR Summary: ${title || 'PR Title'}

## Description
${description || 'No description provided'}

## Changes
This PR introduces the following changes:

`;
    
    if (selectedChanges && selectedChanges.length > 0) {
      selectedChanges.forEach(change => {
        content += `- ${changeTypes[change] || change}\n`;
      });
    } else {
      content += `- ${changes.files.map(f => `Updated ${f}`).join('\n- ')}\n`;
    }

    content += `
## Files Changed
${changes.files.map(f => `- \`${f}\``).join('\n')}

## Statistics
- **Lines added:** ${changes.additions}
- **Lines deleted:** ${changes.deletions}
- **Files changed:** ${changes.files.length}

`;

    if (includeTesting !== false) {
      content += `
## Testing Instructions
1. Checkout this branch: \`git checkout ${branch || 'feature-branch'}\`
2. Run tests: \`npm test\`
3. Test manually using: \`npm start\`
4. Verify the changes work as expected
`;
    }

    if (includeChecklist !== false) {
      content += `
## Checklist
- [ ] Code follows project style guidelines
- [ ] Tests have been added/updated
- [ ] Documentation has been updated
- [ ] All tests pass locally
- [ ] No new warnings/errors in console
- [ ] Performance impact has been considered
- [ ] Security implications have been reviewed
`;
    }

    content += `
## Breaking Changes
${this.config.breakingChanges ? '⚠️ Yes - please see below' : 'None'}

## Related Issues
Closes #(issue number)

## Screenshots (if applicable)
N/A

---
*Generated by PR Summary CLI Tool*
`;

    return content;
  }

  async saveFile(content) {
    const outputPath = this.config.output || './PR_SUMMARY.md';
    await fs.writeFile(outputPath, content);
    console.log(chalk.green(`📄 PR summary written to ${outputPath}`));
  }
}

module.exports = {
  generatePRSummary: async (config) => {
    const generator = new PRSummaryGenerator(config);
    return generator.generate();
  }
};